name: Indicators

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:

  test:
    name: unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
          dotnet-quality: "ga"

      - name: Build solution
        run: >
          dotnet build
          --configuration Release
          --property:ContinuousIntegrationBuild=true
          -warnAsError

      - name: Test indicators
        id: test-api
        run: >
          dotnet test test/Tests.csproj
          --configuration Release
          --no-build
          --verbosity normal
          --logger trx
          --collect:"XPlat Code Coverage"
          --results-directory ./test-results

      - name: Update tests summary
        uses: bibipkins/dotnet-test-reporter@v1.3.3
        if: ${{ github.event_name == 'pull_request' && (success() || (failure() && steps.test-api.conclusion == 'failure')) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: ""
          results-path: ./test-results/**/*.trx
          coverage-path: ./test-results/**/coverage.cobertura.xml
          coverage-type: cobertura
